### ISSUE TITLE
做的很nice

### ISSUE THREAD

**Issue by pengxinseo** [tommm2/jinrup.dev#47]
做的很nice

**Comment by pengxinseo** [comment]
假设 我的几千个文章 velite后  在一个post json中会不会导致数据很大，影响性能 ？ 我准备做多语言的

**Comment by tommm2** [comment]
你說的影響性能是指哪方面的?

**Comment by pengxinseo** [comment]
加载渲染速度，假设有 1000多篇文章，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月22日(星期六) 晚上10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tommm2/jinrup.dev] 做的很nice (Issue #47)














 
你說的影響性能是指哪方面的?

**Comment by tommm2** [comment]
直接渲染 1000 多篇鐵定爆炸，解決方法應該是可以有分頁功能之類的，但我覺得有 1000 多篇文章有蠻難的哈哈

**Comment by pengxinseo** [comment]
我想实现&nbsp; 静态 1000多个页面 多语言的&nbsp; 实现&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月22日(星期六) 晚上10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tommm2/jinrup.dev] 做的很nice (Issue #47)














 
直接渲染 1000 多篇鐵定爆炸，解決方法應該是可以有分頁功能之類的，但我覺得有 1000 多篇文章有蠻難的哈哈

**Comment by tommm2** [comment]
1000 多頁我也沒試過，你可以試試看
